import { Injectable, inject } from '@angular/core'; import { SupabaseService } from './supabase.service'; import { AuthService } from './auth.service'; import { Box, Item, Location, Owner } from './models'; import { PhotoService } from './photo.service';
@Injectable({providedIn:'root'}) export class DataService {
 private sb=inject(SupabaseService).client; private auth=inject(AuthService); private photos=inject(PhotoService); categories=['Electrónica','Cables y cargadores','Herramientas','Documentos','Ropa','Decoración','Cocina','Limpieza','Juegos y consolas','Recuerdos','Otros'];
 household(){return this.auth.profile()!.household_id;} currentOwner(){return this.auth.profile()!.display_name;} visibleOwners(){return [this.currentOwner(),'Compartido'];}
 async locations(includeDeleted=false,scope:'visible'|'all'='visible'){let q=this.sb.from('locations').select('*').eq('household_id',this.household()).order('name'); if(!includeDeleted)q=q.is('deleted_at',null); if(scope==='visible')q=q.in('owner',this.visibleOwners()); const {data,error}=await q;if(error)throw error;return data as Location[];}
 async boxes(includeDeleted=false,scope:'visible'|'all'='visible'){let q=this.sb.from('boxes').select('*').eq('household_id',this.household()).order('name');if(!includeDeleted)q=q.is('deleted_at',null);if(scope==='visible')q=q.in('owner',this.visibleOwners());const {data,error}=await q;if(error)throw error;return data as Box[];}
 async items(includeDeleted=false,scope:'visible'|'all'='visible'){let q=this.sb.from('items').select('*').eq('household_id',this.household()).order('name');if(!includeDeleted)q=q.is('deleted_at',null);if(scope==='visible')q=q.in('owner',this.visibleOwners());const {data,error}=await q;if(error)throw error;return data as Item[];}
 async addLocation(v:{name:string,type:string,parent_id:string|null,owner:Owner,notes?:string}){const {error}=await this.sb.from('locations').insert({...v,household_id:this.household(),created_by_profile:this.auth.profile()!.id});if(error)throw error;}
 async addBox(v:{name:string,description?:string,category?:string,owner:Owner,location_id:string|null,parent_box_id:string|null},file?:File){const {data,error}=await this.sb.from('boxes').insert({...v,household_id:this.household(),created_by_profile:this.auth.profile()!.id}).select().single();if(error)throw error;if(file){const path=await this.upload(file,`households/${this.household()}/boxes/${data.id}/exterior.webp`);await this.sb.from('boxes').update({exterior_photo_path:path}).eq('id',data.id);}}
 async addItem(v:{name:string,description?:string,category?:string,owner:Owner,location_id:string|null,box_id:string|null},file?:File){const {data,error}=await this.sb.from('items').insert({...v,household_id:this.household(),created_by_profile:this.auth.profile()!.id}).select().single();if(error)throw error;if(file){const path=await this.upload(file,`households/${this.household()}/items/${data.id}/photo.webp`);await this.sb.from('items').update({photo_path:path}).eq('id',data.id);}}
 async updateLocation(id:string,v:{name:string,type:string,parent_id:string|null,owner:Owner,notes?:string}){const {error}=await this.sb.from('locations').update(v).eq('id',id).eq('household_id',this.household());if(error)throw error;}
 async updateBox(id:string,v:{name:string,description?:string,category?:string,owner:Owner,location_id:string|null,parent_box_id:string|null},file?:File){const patch:any={...v};if(file)patch.exterior_photo_path=await this.upload(file,`households/${this.household()}/boxes/${id}/exterior.webp`);const {error}=await this.sb.from('boxes').update(patch).eq('id',id).eq('household_id',this.household());if(error)throw error;}
 async updateItem(id:string,v:{name:string,description?:string,category?:string,owner:Owner,location_id:string|null,box_id:string|null},file?:File){const patch:any={...v};if(file)patch.photo_path=await this.upload(file,`households/${this.household()}/items/${id}/photo.webp`);const {error}=await this.sb.from('items').update(patch).eq('id',id).eq('household_id',this.household());if(error)throw error;}
 async upload(file:File,path:string){const blob=await this.photos.compress(file);const {error}=await this.sb.storage.from('household-images').upload(path,blob,{contentType:'image/webp',upsert:true});if(error)throw error;return path;}
 async signed(path:string|null){if(!path)return null;const {data}=await this.sb.storage.from('household-images').createSignedUrl(path,3600);return data?.signedUrl??null;}
 async remove(table:'locations'|'boxes'|'items',id:string){const {error}=await this.sb.from(table).update({deleted_at:new Date().toISOString()}).eq('id',id);if(error)throw error;}
 async restore(table:'locations'|'boxes'|'items',id:string){const {error}=await this.sb.from(table).update({deleted_at:null}).eq('id',id);if(error)throw error;}
 async search(term:string,scope:'mine'|'shared'='mine'){const words=term.trim().replace(/[,%()]/g,' '); if(!words)return {boxes:[],items:[]}; let b=this.sb.from('boxes').select('*').is('deleted_at',null).or(`name.ilike.%${words}%,description.ilike.%${words}%,category.ilike.%${words}%`); let i=this.sb.from('items').select('*').is('deleted_at',null).or(`name.ilike.%${words}%,description.ilike.%${words}%,category.ilike.%${words}%`); if(scope==='mine'){b=b.in('owner',this.visibleOwners());i=i.in('owner',this.visibleOwners());}else{b=b.eq('owner','Compartido');i=i.eq('owner','Compartido');} const [br,ir]=await Promise.all([b, i]); if(br.error)throw br.error;if(ir.error)throw ir.error; const rank=(x:any)=>x.name.toLowerCase().startsWith(term.toLowerCase())?0:x.name.toLowerCase().includes(term.toLowerCase())?1:2; return {boxes:(br.data as Box[]).sort((a,b)=>rank(a)-rank(b)),items:(ir.data as Item[]).sort((a,b)=>rank(a)-rank(b))};}
}
